worker_processes 1;

events { worker_connections 1024; }

http {
  access_log /dev/stdout;
  error_log  /dev/stderr;

  upstream users_upstream     { server users:3000; }
  upstream events_upstream    { server events:5000; }
  upstream purchases_upstream { server purchases:5003; }
  # notifications no se expone vía Nginx

  server {
    listen 80;

    location /auth/ {
      proxy_pass http://users_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

    location /events/ {
      proxy_pass http://events_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

    location /purchases/ {
      proxy_pass http://purchases_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

    location = /health {
      return 200 "ok";
      add_header Content-Type text/plain;
    }
  }
}
