services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI: http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  users-svc:
    build: ./users-svc
    environment:
      PORT: 4001
    ports:
      - "4001:4001"

  orders-svc:
    build: ./orders-svc
    container_name: orders-svc
    depends_on:
      - users-svc
      - rabbitmq
    environment:
      PORT: 4002
      USERS_URL: http://users-svc:4001
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      EXCHANGE: domain.events
      ROUTING_KEY: order.created
    ports:
      - "4002:4002"

  api-gateway:
    image: nginx:alpine
    depends_on: [ users-svc, orders-svc ]
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro

  notifications-worker:
    build: ./notifications-worker
    container_name: notifications-worker
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      EXCHANGE: domain.events
      QUEUE: notifications.order.created
      ROUTING_KEY: order.created
